# An abbreviated quick reference

This notebook explains some tools used in the other notebooks in quick reference format.
Please refer to the hints here for help with the other notebooks.

# Lists and Tuples

In [1]:
# Lists and tuples:  Below is a list of tuples
points = [
    (0,6),
    (3,0),
    (10,2),
    (12,9),
    (9,12),
    (6,17)
]

In [2]:
# Lists and tuples have a lot of useful features
print("the first point is", points[0])
print("the second point is", points[1])
print("the last point is", points[-1])
print("There are", len(points), "points")

the first point is (0, 6)
the second point is (3, 0)
the last point is (6, 17)
There are 6 points


In [3]:
# One of the most useful things you can do with lists (and tuples) is iterate over their members
total_x = 0
for point in points:
    (x, y) = point
    total_x = total_x + x
    
# (Purists will object that there are better/alternative ways to do the above
# but here we keep things simple for now.)
print("the total of x's is", total_x, "and the average x value is", total_x/len(points))

the total of x's is 40 and the average x value is 6.666666666666667


In [4]:
# You can change lists
my_list = [1,2,3]
my_list[2] = 5
my_list

[1, 2, 5]

In [ ]:
# You can't change tuples at the "top level"
my_tuple = (1,2,3)
my_tuple[2] = 5
my_tuple

In [7]:
# enumeration in looping
for (index, location) in enumerate(points):
    print ("   point[", index, "] has value ", location)

   point[ 0 ] has value  (0, 6)
   point[ 1 ] has value  (3, 0)
   point[ 2 ] has value  (10, 2)
   point[ 3 ] has value  (12, 9)
   point[ 4 ] has value  (9, 12)
   point[ 5 ] has value  (6, 17)


# Dictionaries and sets

In [9]:
# A calculated dictionary
double = {}  # make an empty Dictionary.

for i in range(10):
    double[i] = i * 2
    
double

{0: 0, 1: 2, 2: 4, 3: 6, 4: 8, 5: 10, 6: 12, 7: 14, 8: 16, 9: 18}

In [10]:
# Get a value for a key
print ("the double of", 3, "is", double[3])

# Iterate across all keys in a for loop:
for key in double:
    value = double[key]
    print ("   ", key, "doubled is", value)
    
# get lists of all keys and all values
print ("all keys", list(double.keys()))
print ("all values", list(double.values()))


the double of 3 is 6
    0 doubled is 0
    1 doubled is 2
    2 doubled is 4
    3 doubled is 6
    4 doubled is 8
    5 doubled is 10
    6 doubled is 12
    7 doubled is 14
    8 doubled is 16
    9 doubled is 18
all keys [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
all values [0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [12]:
# A non-empty dictionary literal
male_female = {
    "king": "queen",
    "man": "woman",
    "micky": "minny",
    "clyde": "bonnie",
}
print ("the female equivalent of 'king' is", repr(male_female["king"]))

the female equivalent of 'king' is 'queen'


# Arrays and numeric python

Just what we need here (there's a lot more)...

In [13]:
# The primary module is numpy usually abbreviated to np
import numpy as np
np.set_printoptions(precision=4)  # Don't show too many decimals

# Make a literal array
x = np.array([1, 1, 2, 3, 5, 8, 13], dtype=np.float)
x

array([ 1.,  1.,  2.,  3.,  5.,  8., 13.])

In [14]:
# arithmetic
1/x

array([1.    , 1.    , 0.5   , 0.3333, 0.2   , 0.125 , 0.0769])

In [16]:
x ** 2

array([  1.,   1.,   4.,   9.,  25.,  64., 169.])

In [17]:
x ** 2 - 3 * x + 4

array([  2.,   2.,   2.,   4.,  14.,  44., 134.])

In [18]:
# numpy also has common numeric functions like sin, and cos generalized to arrays
np.sin(x * 0.1)

array([0.0998, 0.0998, 0.1987, 0.2955, 0.4794, 0.7174, 0.9636])

In [19]:
# Create an array with seven numbers uniformly between -1 and 2
np.linspace(-1, 2, 7)

array([-1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ])